# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cab7cada3f60c984a74843fcc3f3ee0d63f5a113d25b198770c82292ff4bf2fd438f87f33ac5a14384d8318cc7bfeab5651389464b79c083aa56d9deca1cd74c

test:
  secret_key_base: 2ecada2adbb2ce681aa9c625cc7c4d03fc8cc8abcbfc27085fbbebce150f46fa2555c0c759e6bdad10511d4eebe153bf7377add605b3c3673ddd55ab0dccb852

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
